# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: "America/New_York"
    target-branch: dev
    commit-message:
      prefix: "chore: update submodule"
